apiVersion: v1
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9yb290LXVzZXI6OTlhVE1nUDNIQTVHeXRBdUBhdXRoLW1pY3Jvc2VydmljZS1kYi5heGpwdy5tb25nb2RiLm5ldC9BdXRoRGI=
  JWT_SECRET: WEJ0YVJLMWU5STlMOFp3aDdSTWFPcFJQdnJIOE1CMW9aRDNSUGxCNjRtMnBWUEVlRjNhVkRxV2poag==
kind: Secret
metadata:
  creationTimestamp: "2025-03-25T15:07:03Z"
  name: auth-ms
  namespace: default
  resourceVersion: "79765"
  uid: 9155f593-82f3-44d2-9a15-d33561192e20
type: Opaque
